[options]
admin_passwd = ${ODOO_ADMIN_PASSWD}
db_host = db
db_port = 5432
db_user = ${POSTGRES_USER}
db_password = ${POSTGRES_PASSWORD}
db_name = ${DB_NAME}
data_dir = /var/lib/odoo
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons,/mnt/extra-addons/custom,/mnt/extra-addons/oca/web,/mnt/extra-addons/oca/website,/mnt/extra-addons/oca/e-commerce,/mnt/extra-addons/oca/sale-workflow,/mnt/extra-addons/oca/account-financial-tools,/mnt/extra-addons/oca/stock-logistics-workflow,/mnt/extra-addons/oca/management-system,/mnt/extra-addons/oca/server-ux,/mnt/extra-addons/oca/server-tools
http_interface = ${ODOO_HTTP_INTERFACE}
http_port = ${ODOO_HTTP_PORT}
gevent_port = ${ODOO_LONGPOLLING_PORT}
proxy_mode = True
list_db = True
workers = 0
limit_time_real = 600
limit_memory_hard = 0
log_handler = :INFO
log_level = info
