{
    "name": "Steamships Trading (PNG) Demo",
    "version": "18.0.1.0.8",
    "category": "Demo",
    "summary": "Steamships Trading Company (PNG) - Shipping, Property, Hotels, Logistics",
    "author": "Steamships Prototype",
    "license": "LGPL-3",
    "depends": [
        "base",
        "crm",
        "sale",
        "sale_management",
        "account",
        "contacts",
        "product",
        "website",
        "calendar",
        "utm",
        "mail",
    ],
    "data": [
        "data/assets.xml",
        "security/streamships_groups.xml",
        "security/ir.model.access.csv",
        "data/res_company_data.xml",
        "data/res_currency_data.xml",
        "data/division_data.xml",
        "data/branch_data.xml",
        "data/product_category_data.xml",
        "data/product_data.xml",
        "data/product_pricelist_data.xml",
        "data/sample_bl_scans.xml",
        "data/crm_team_data.xml",
        "data/res_users_data.xml",
        "data/crm_stages.xml",
        "data/crm_lead_data.xml",
        "data/ir_sequence_data.xml",
        "data/ir_paperformat_data.xml",
        "data/mail_templates.xml",
        "data/ir_cron_data.xml",
        "views/division_views.xml",
        "views/branch_views.xml",
        "views/crm_lead_views.xml",
        "views/sale_order_views.xml",
        "views/product_views.xml",
        "views/chat_widget_views.xml",
        "views/bill_of_lading_views.xml",
        "views/appointment_slot_views.xml",
        "views/menu_views.xml",
        "views/onboarding_form.xml",
        "views/booking_form.xml",
        "views/website_branding.xml",
        "views/report_header_footer.xml",
        "views/report_saleorder.xml",
        "views/ir_actions_report_override.xml",
        "wizards/crm_lead_onboarding_wizard_view.xml",
    ],
    "assets": {},
    "demo": [
        "demo/demo_quotations.xml",
    ],
    "application": True,
    "installable": True,
    "auto_install": False,
}
